services:

  service:
    image: ffcadcaed-sc
    container_name: ffcadcaed-service
    stop_grace_period: 1s
    depends_on:
      - kdc
    #ports:
    #  - "3443:3443"
    volumes:
      - keytabs:/_keytabs
    environment:
      - KRB5_CONFIG=/app/_krbbrb/krb5.conf
      - KRB5CCNAME=MEMORY:service
      - KRB5_TRACE=
    networks:
      - net
    command: make run-service KEYTABS_DIR=/_keytabs

  client:
    restart: no
    image: ffcadcaed-sc
    container_name: ffcadcaed-client
    stop_grace_period: 1s
    depends_on:
      - service
    volumes:
      - keytabs:/_keytabs
    environment:
      - KRB5_CONFIG=/app/_krbbrb/krb5.conf
      - KRB5CCNAME=/tmp/krb5cc
      - KRB5_TRACE=
    networks:
      - net
    command: >
      /bin/bash -c "sleep 2; make kinit-init-client run-client-curl run-client KEYTABS_DIR=/_keytabs SERVICE_HOST=service"

  kdc:
    image: ffcadcaed-kdc
    container_name: ffcadcaed-kdc
    stop_grace_period: 1s
    # ports:
    #  - "9988:88"
    #  - "9749:749"
    volumes:
      - kdc:/var/kerberos/krb5kdc
      - keytabs:/_keytabs
    environment:
      - KRB5_CONFIG=/etc/krb5.conf
      - KRB5_TRACE=
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  kdc:
  keytabs:
